# imports math module to work with math
import math 
# imports datetime for date and time
import datetime
# imports random module for pseudorandom number generation
import random
# imports os module
import os
# imports requests, allows for http requests to be made easily
import requests
# imports re, to manipulate strings.
import re

# Prints out square root of 16 using math
print ("The square root of 16 is",math.sqrt(16))

# Prints out the value of pi using math
print("Pi is",math.pi)

# Prints the factorial of a number using math.factorial
print("The factorial of 4 is",math.factorial(4))

# Prints greatest common denominator of 10 using math.gcd
print("The GCD of 10 is", math.gcd(10))

# Prints sin cos tan of 90 using math.sin, math.cos, and math.tan
print("Sine, cosine, and tangent of 90 is",math.sin(90),",",math.cos(90),", and",math.tan(90))



# Gets date and time using python's date and time module
print("The date and time is", datetime.datetime.now())

# Gets difference between dates
t1 = datetime.datetime.now()
t2 = datetime.datetime(2000, 12, 20, 0, 0)
print("The time from my birthday is",t1-t2)

# Different formats...
print("The current date is", t1.strftime("%x"))
print("The current date is also", t1.strftime("%c"))



# Generates a random number between 1-10
print(random.randint(1, 10),"is a random number generated by python random module")

# Shuffles a list
myList = [1, 2, 3, 4, 5, 6, 7, 8]
random.shuffle(myList)
print(myList)

# Selects a random element from a list
print(random.choice(myList))



# Lists directory then prints
dirList = os.listdir()
print(dirList)

# Makes new folder in specified directory
#os.mkdir("c:/test")

# Gets current working directory then prints
workDir = os.getcwd()
print(workDir)




# Makes GET request to a public website and prints response.
website = requests.get("https://www.weather.gov/documentation/services-web-api")
print(website)

website2 = requests.post("https://www.weather.gov/documentation/services-web-api")
print(website2)



# Finds all occurences of a pattern in a string.
find = re.findall("weather", website.text)
print("There are",len(find),"instances of the word weather in the website given.")
webModify = re.sub("weather", "not weather", website.text)
print(webModify)